env:
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - "prettier"
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 9
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules: 
    - "no-unresolved": false,
    - "no-param-reassign": "off",
    - "prettier/prettier": [
      "error",
      {
        endOfLine: "auto",
      },
    ],